format = """
$username$hostname$shell$sudo $git_status$git_state$git_commit$fill$battery | $memory_usage
$cmd_duration $directory$git_branch$character"""

right_format = """$python$time"""


[username]
show_always = true
format = "[$user on](bold cyan)"

[hostname]
ssh_only = false
format = "[ $hostname](bold yellow)"

[shell]
disabled = false
elvish_indicator = 'elv'
unknown_indicator = '?sh'
format = '[ using $indicator]($style)'

[sudo]
style = 'bold green'
symbol = 'sudo'
disabled = false
format = '[ as $symbol]($style)'

[git_status]
conflicted = "!"
ahead = "^${count}"
behind = "v${count}"
diverged = "<${ahead_count}${behind_count}>"
deleted = "x"
modified = "m"
staged = '[++\($count\)](green)'
renamed = "r"
stashed = "s"

[battery]
full_symbol = ":3"
charging_symbol = "++"
discharging_symbol = "--"
unknown_symbol = "?"
empty_symbol = ":x"
format = '[ $percentage \($symbol\)]($style)'

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 20
style = 'red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[[battery.display]]
threshold = 50
style = 'yellow'

[[battery.display]]
threshold = 70
style = 'green'

[[battery.display]]
threshold = 100
style = 'bold green'

[memory_usage]
disabled = false
symbol = "ram: "
style = "bold green"
format = "[ram: $ram]($style)"
threshold = -1


[cmd_duration]
format = "[$duration](yellow)"
min_time = 1

[directory]
truncate_to_repo = false
read_only = 'x'
truncation_length = 3
truncation_symbol = "…"
before_repo_root_style = "blue"
repo_root_style = "bold blue"
style = "bold"
format = ' [$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = ""
always_show_remote = true

[character]
success_symbol = "[:3](bold green)"
error_symbol = "[:x](bold red)"


[python]
symbol = "py"
format = ' [${pyenv_prefix} \($virtualenv\)](blue) via [${symbol} (${version})]($style) |'

[time]
format = "[ $time](bold cyan)"
time_format = "%H:%M"
disabled = false
